## Read Parquet

In [12]:
import pandas as pd

df = pd.read_parquet("../data/aggregations/by_case.parquet")
pd.set_option("display.max_rows", None)

display(pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str)
}))


df =  pd.read_parquet("../data/aggregations/by_judge.parquet")

display(pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str)
}))

,column,dtype
ucid,ucid,object
los_days,los_days,int64
case_open_date,case_open_date,object
n_events,n_events,int64
n_activity_types,n_activity_types,int64
n_motions,n_motions,int64
activity_entropy,activity_entropy,float64
case_type,case_type,object
city,city,object
is_mdl,is_mdl,bool
District_Judge,District_Judge,object
Magistrate_Judge,Magistrate_Judge,bool
plaintiffs_count,plaintiffs_count,float64
plaintiffs_share_ind,plaintiffs_share_ind,float64
plaintiffs_share_pro_se,plaintiffs_share_pro_se,float64
plaintiffs_share_pro_hac_vice,plaintiffs_share_pro_hac_vice,float64
plaintiffs_counsels_count,plaintiffs_counsels_count,float64
Defendants_count,Defendants_count,float64
Defendants_share_ind,Defendants_share_ind,float64
Defendants_share_pro_se,Defendants_share_pro_se,float64
Defendants_share_pro_hac_vice,Defendants_share_pro_hac_vice,float64
Defendants_counsels_count,Defendants_counsels_count,float64
Defendants_pending_counts,Defendants_pending_counts,float64
Defendants_terminated_counts,Defendants_terminated_counts,float64
Other_courts,Other_courts,int64
related_case_count,related_case_count,int64
Party_Amicus,Party_Amicus,int64
Party_Counter_Claimant,Party_Counter_Claimant,int64
Party_Counter_Defendant,Party_Counter_Defendant,int64
Party_Court_Monitor,Party_Court_Monitor,int64
Party_Intervenor,Party_Intervenor,int64
Party_Material_Witness,Party_Material_Witness,int64
Party_Third_Party_Defendant,Party_Third_Party_Defendant,int64
Party_Third_Party_Plaintiff,Party_Third_Party_Plaintiff,int64
Party_Trustee,Party_Trustee,int64
sum_attribute_scheduling,sum_attribute_scheduling,float64
sum_attribute_rescheduling,sum_attribute_rescheduling,float64
sum_attribute_hearing_conf,sum_attribute_hearing_conf,float64
sum_attribute_dismiss_without_prejudice,sum_attribute_dismiss_without_prejudice,float64
sum_attribute_dismissal_other,sum_attribute_dismissal_other,float64
sum_attribute_dispositive,sum_attribute_dispositive,float64
sum_attribute_granting_motion_to_dismiss,sum_attribute_granting_motion_to_dismiss,float64
sum_attribute_motion_other,sum_attribute_motion_other,float64
sum_attribute_motion_to_dismiss,sum_attribute_motion_to_dismiss,float64
sum_attribute_notice_other,sum_attribute_notice_other,float64
sum_attribute_opening,sum_attribute_opening,float64
sum_attribute_plea_guilty,sum_attribute_plea_guilty,float64
sum_attribute_plea_not_guilty,sum_attribute_plea_not_guilty,float64
sum_attribute_bilateral_unopposed,sum_attribute_bilateral_unopposed,float64
sum_attribute_motion_for_time_extension,sum_attribute_motion_for_time_extension,float64
sum_attribute_petition_other,sum_attribute_petition_other,float64
sum_attribute_proposed,sum_attribute_proposed,float64
sum_attribute_waiver_of_indictment,sum_attribute_waiver_of_indictment,float64
sum_attribute_memo_opinion,sum_attribute_memo_opinion,float64
sum_attribute_motion_for_judgment_other,sum_attribute_motion_for_judgment_other,float64
sum_attribute_notice_of_appeal,sum_attribute_notice_of_appeal,float64
sum_attribute_notice_of_motion,sum_attribute_notice_of_motion,float64
sum_attribute_petition_for_habeas_corpus,sum_attribute_petition_for_habeas_corpus,float64
sum_attribute_motion_for_dismissal_other,sum_attribute_motion_for_dismissal_other,float64
sum_attribute_motion_for_voluntary_dismissal,sum_attribute_motion_for_voluntary_dismissal,float64
sum_attribute_motion_to_seal,sum_attribute_motion_to_seal,float64
sum_attribute_voluntary_dismissal,sum_attribute_voluntary_dismissal,float64
sum_attribute_transfer_outbound,sum_attribute_transfer_outbound,float64
sum_attribute_motion_for_default_judgment,sum_attribute_motion_for_default_judgment,float64
sum_attribute_dismiss_with_prejudice,sum_attribute_dismiss_with_prejudice,float64
sum_attribute_granting_motion_for_summary_judgment,sum_attribute_granting_motion_for_summary_judg...,float64
sum_attribute_motion_for_summary_judgment,sum_attribute_motion_for_summary_judgment,float64
sum_attribute_waiver_other,sum_attribute_waiver_other,float64
sum_attribute_remand,sum_attribute_remand,float64
sum_attribute_stipulation_other,sum_attribute_stipulation_other,float64
sum_attribute_trial_jury,sum_attribute_trial_jury,float64
sum_attribute_motion_for_habeas_corpus,sum_attribute_motion_for_habeas_corpus,float64
sum_attribute_default_judgment,sum_attribute_default_judgment,float64
sum_attribute_transfer_unknown,sum_attribute_transfer_unknown,float64
sum_attribute_stipulation_of_dismissal,sum_attribute_stipulation_of_dismissal,float64
sum_attribute_motion_for_arbitration,sum_attribute_motion_for_arbitration,float64
sum_attribute_motion_to_remand,sum_attribute_motion_to_remand,float64
sum_attribute_motion_to_certify_class,sum_attribute_motion_to_certify_class,float64
sum_attribute_notice_of_consent,sum_attribute_notice_of_consent,float64
sum_attribute_settlement_rule_68,sum_attribute_settlement_rule_68,float64
sum_attribute_transfer_inbound,sum_attribute_transfer_inbound,float64
sum_attribute_motion_for_settlement,sum_attribute_motion_for_settlement,float64
sum_attribute_motion_for_judgment_on_the_pleadings,sum_attribute_motion_for_judgment_on_the_plead...,float64
sum_attribute_trial_other,sum_attribute_trial_other,float64
sum_attribute_trial_bench,sum_attribute_trial_bench,float64
sum_attribute_stipulation_for_judgment,sum_attribute_stipulation_for_judgment,float64
sum_attribute_notice_of_voluntary_dismissal,sum_attribute_notice_of_voluntary_dismissal,float64
sum_attribute_notice_of_dismissal_other,sum_attribute_notice_of_dismissal_other,float64
sum_attribute_motion_for_judgment_as_a_matter_of_law,sum_attribute_motion_for_judgment_as_a_matter_...,float64
sum_attribute_settlement_consent_decree,sum_attribute_settlement_consent_decree,float64
sum_attribute_case_opened_in_error,sum_attribute_case_opened_in_error,float64
sum_attribute_admin_closing,sum_attribute_admin_closing,float64
sum_attribute_stipulation_for_settlement,sum_attribute_stipulation_for_settlement,float64
sum_attribute_notice_of_settlement,sum_attribute_notice_of_settlement,float64
log_los_days,log_los_days,float64
complexity_index,complexity_index,float64

,column,dtype
District_Judge,District_Judge,object
n_cases,n_cases,int64
los_mean,los_mean,float64
los_median,los_median,float64
los_std,los_std,float64
log_los_mean,log_los_mean,float64
n_events_mean,n_events_mean,float64
n_activity_types_mean,n_activity_types_mean,float64
n_motions_mean,n_motions_mean,float64
activity_entropy_mean,activity_entropy_mean,float64
complexity_index_mean,complexity_index_mean,float64
sum_attribute_scheduling_mean,sum_attribute_scheduling_mean,float64
sum_attribute_rescheduling_mean,sum_attribute_rescheduling_mean,float64
sum_attribute_hearing_conf_mean,sum_attribute_hearing_conf_mean,float64
sum_attribute_dismiss_without_prejudice_mean,sum_attribute_dismiss_without_prejudice_mean,float64
sum_attribute_dismissal_other_mean,sum_attribute_dismissal_other_mean,float64
sum_attribute_dispositive_mean,sum_attribute_dispositive_mean,float64
sum_attribute_granting_motion_to_dismiss_mean,sum_attribute_granting_motion_to_dismiss_mean,float64
sum_attribute_motion_other_mean,sum_attribute_motion_other_mean,float64
sum_attribute_motion_to_dismiss_mean,sum_attribute_motion_to_dismiss_mean,float64
sum_attribute_notice_other_mean,sum_attribute_notice_other_mean,float64
sum_attribute_opening_mean,sum_attribute_opening_mean,float64
sum_attribute_plea_guilty_mean,sum_attribute_plea_guilty_mean,float64
sum_attribute_plea_not_guilty_mean,sum_attribute_plea_not_guilty_mean,float64
sum_attribute_bilateral_unopposed_mean,sum_attribute_bilateral_unopposed_mean,float64
sum_attribute_motion_for_time_extension_mean,sum_attribute_motion_for_time_extension_mean,float64
sum_attribute_petition_other_mean,sum_attribute_petition_other_mean,float64
sum_attribute_proposed_mean,sum_attribute_proposed_mean,float64
sum_attribute_waiver_of_indictment_mean,sum_attribute_waiver_of_indictment_mean,float64
sum_attribute_memo_opinion_mean,sum_attribute_memo_opinion_mean,float64
sum_attribute_motion_for_judgment_other_mean,sum_attribute_motion_for_judgment_other_mean,float64
sum_attribute_notice_of_appeal_mean,sum_attribute_notice_of_appeal_mean,float64
sum_attribute_notice_of_motion_mean,sum_attribute_notice_of_motion_mean,float64
sum_attribute_petition_for_habeas_corpus_mean,sum_attribute_petition_for_habeas_corpus_mean,float64
sum_attribute_motion_for_dismissal_other_mean,sum_attribute_motion_for_dismissal_other_mean,float64
sum_attribute_motion_for_voluntary_dismissal_mean,sum_attribute_motion_for_voluntary_dismissal_mean,float64
sum_attribute_motion_to_seal_mean,sum_attribute_motion_to_seal_mean,float64
sum_attribute_voluntary_dismissal_mean,sum_attribute_voluntary_dismissal_mean,float64
sum_attribute_transfer_outbound_mean,sum_attribute_transfer_outbound_mean,float64
sum_attribute_motion_for_default_judgment_mean,sum_attribute_motion_for_default_judgment_mean,float64
sum_attribute_dismiss_with_prejudice_mean,sum_attribute_dismiss_with_prejudice_mean,float64
sum_attribute_granting_motion_for_summary_judgment_mean,sum_attribute_granting_motion_for_summary_judg...,float64
sum_attribute_motion_for_summary_judgment_mean,sum_attribute_motion_for_summary_judgment_mean,float64
sum_attribute_waiver_other_mean,sum_attribute_waiver_other_mean,float64
sum_attribute_remand_mean,sum_attribute_remand_mean,float64
sum_attribute_stipulation_other_mean,sum_attribute_stipulation_other_mean,float64
sum_attribute_trial_jury_mean,sum_attribute_trial_jury_mean,float64
sum_attribute_motion_for_habeas_corpus_mean,sum_attribute_motion_for_habeas_corpus_mean,float64
sum_attribute_default_judgment_mean,sum_attribute_default_judgment_mean,float64
sum_attribute_transfer_unknown_mean,sum_attribute_transfer_unknown_mean,float64
sum_attribute_stipulation_of_dismissal_mean,sum_attribute_stipulation_of_dismissal_mean,float64
sum_attribute_motion_for_arbitration_mean,sum_attribute_motion_for_arbitration_mean,float64
sum_attribute_motion_to_remand_mean,sum_attribute_motion_to_remand_mean,float64
sum_attribute_motion_to_certify_class_mean,sum_attribute_motion_to_certify_class_mean,float64
sum_attribute_notice_of_consent_mean,sum_attribute_notice_of_consent_mean,float64
sum_attribute_settlement_rule_68_mean,sum_attribute_settlement_rule_68_mean,float64
sum_attribute_transfer_inbound_mean,sum_attribute_transfer_inbound_mean,float64
sum_attribute_motion_for_settlement_mean,sum_attribute_motion_for_settlement_mean,float64
sum_attribute_motion_for_judgment_on_the_pleadings_mean,sum_attribute_motion_for_judgment_on_the_plead...,float64
sum_attribute_trial_other_mean,sum_attribute_trial_other_mean,float64
sum_attribute_trial_bench_mean,sum_attribute_trial_bench_mean,float64
sum_attribute_stipulation_for_judgment_mean,sum_attribute_stipulation_for_judgment_mean,float64
sum_attribute_notice_of_voluntary_dismissal_mean,sum_attribute_notice_of_voluntary_dismissal_mean,float64
sum_attribute_notice_of_dismissal_other_mean,sum_attribute_notice_of_dismissal_other_mean,float64
sum_attribute_motion_for_judgment_as_a_matter_of_law_mean,sum_attribute_motion_for_judgment_as_a_matter_...,float64
sum_attribute_settlement_consent_decree_mean,sum_attribute_settlement_consent_decree_mean,float64
sum_attribute_case_opened_in_error_mean,sum_attribute_case_opened_in_error_mean,float64
sum_attribute_admin_closing_mean,sum_attribute_admin_closing_mean,float64
sum_attribute_stipulation_for_settlement_mean,sum_attribute_stipulation_for_settlement_mean,float64
sum_attribute_notice_of_settlement_mean,sum_attribute_notice_of_settlement_mean,float64
pct_cv,pct_cv,float64
los_p25,los_p25,float64
los_p75,los_p75,float64
los_p90,los_p90,float64